apiVersion : apps/v1
kind: Deployment
metadata:
  name: prodnginx 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prodnginx
  template:
    metadata:
      labels:
        app: prodnginx 
    spec:
      containers:
        - name: prodnginx 
          image: devvgrmyacr.azurecr.io/prodnginx
          ports:
          - containerPort: 80